namespace: m4eba
name: etcd
version: 0.1.1
readme: README.md
authors:
  - m4eba
description: An ansible collection to install and manage an etcd cluster.
license:
  - MIT
license_file: 'LICENSE'
tags: ['etcd']
dependencies: { community.crypto: '>=2.0.0' }
repository: http://github.com/m4eba/ansible-etcd
issues: http://github.com/m4eba/ansible-etcd/issues
