---
- name: get ip addresses
  hosts: all
  tasks:
    - name: import get ip
      import_tasks: ../resources/roles/get_ip/tasks/main.yaml
- name: prepare cluster
  import_playbook: ../../playbooks/cluster.yaml
