---
- name: get ip addresses
  hosts: all
  tasks:
    - import_role: 
        name: get_ip
- name: add pending to group
  hosts: localhost
  tasks:
    - add_host:
        name: instance4
        groups:
          - etcd
      changed_when: false 
- import_playbook: ../../playbooks/cluster.yaml
