---
- name: get ip addresses
  hosts: all
  tasks:
    - name: import get ip
      import_tasks: ../resources/roles/get_ip/tasks/main.yaml
- name: prepare cluster
  import_playbook: ../../playbooks/cluster.yaml
- name: add pending
  hosts: pendingetcd
  tasks:
    - name: run add command
      delegate_to: instance1
      command: '/opt/etcd/bin/etcdctl --cacert /etc/etcd/pki/ca.crt --key /etc/etcd/pki/etcd.key --cert /etc/etcd/pki/etcd.crt --endpoints https://{{ hostvars["instance1"]["etcd_ip"] }}:2379 member add {{ inventory_hostname }} --peer-urls=https://{{ etcd_ip }}:2380'
      changed_when: add_command_output.rc == 0
      register: add_command_output
