---
- name: get ip
  shell: |
    set -e -o pipefail
    ip -f inet addr show eth0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p'
  changed_when: false
  register: ip_output
- name: set ip fact
  set_fact:
    etcd_ip: '{{ ip_output.stdout }}'