---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: jrei/systemd-ubuntu
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - etcd
provisioner:
  name: ansible
verifier:
  name: ansible
