---
- name: etcd present
  stat:
    path: /opt/etcd/bin/etcd
  register: stat_bin

- name: set installed fact
  set_fact:
    etcd_bin: '{{ stat_bin.stat.exists }}'

- name: get services
  service_facts:

- name: set running fact
  set_fact:
    etcd_running: '{% if ansible_facts.services["etcd.service"] is defined %}{{ ansible_facts.services["etcd.service"].state == "running" }}{% else %}false{% endif %}'

- name: debug etcd_running
  debug:
    var: etcd_running

- name: key file present
  stat:
    path: /etc/etcd/pki/ca.crt
  register: stat_key

- name: key fact
  set_fact:
    etcd_key: '{{ stat_key.stat.exists }}'

- name: members
  command: '/opt/etcd/bin/etcdctl --endpoints https://{{ etcd_ip }}:2379 --cert=/etc/etcd/pki/etcd.crt --key=/etc/etcd/pki/etcd.key --cacert=/etc/etcd/pki/ca.crt member list --write-out json'
  changed_when: false
  register: memberlist_out
  when: etcd_running

- name: members fact
  set_fact:
    etcd_members: '{{ memberlist_out.stdout }}'
  when: etcd_running

- name: set one working member
  delegate_to: localhost
  delegate_facts: true
  set_fact:
    etcd_main: '{{ inventory_hostname }}'
  when: etcd_running

- name: debug members
  debug:
    var: etcd_members
