---
- name: get ip addresses
  hosts: all
  tasks:
    - name: import get ip
      import_tasks: ../resources/roles/get_ip/tasks/main.yaml
- name: prepare groups
  hosts: removeetcd
  tasks:
    - name: add instance4 to etcd group
      add_host:
        name: instance4
        groups:
          - etcd
- name: prepare cluster
  import_playbook: ../../playbooks/cluster.yaml
