---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: etcd
  gather_facts: false
  tasks:
    - name: Example assertion
      include_tasks: ../resources/roles/test_etcd/tasks/main.yaml
