---
- name: CA
  hosts: localhost
  roles:
    - { role: m4eba.etcd.ca, tags: ca }

- name: Collecting facts
  hosts: etcd
  remote_user: root
  roles:
    - { role: m4eba.etcd.facts, tags: facts }

- name: execution plan
  hosts: localhost
  roles:
    - { role: m4eba.etcd.plan, tags: plan }

- name: remove commands
  hosts: etcd_modify
  remote_user: root
  roles:
    - role: m4eba.etcd.remove
      tags: remove
      when: hostvars['localhost']['etcd_main'] is defined

- name: prepare
  hosts: etcd
  remote_user: root
  roles:
    - { role: m4eba.etcd.prepare, tags: prepare }

- name: pki
  hosts: etcd
  remote_user: root
  roles:
    - role: m4eba.etcd.pki
      tags: pki
      when: not etcd_key

- name: init etcd
  hosts: etcd
  remote_user: root
  roles:
    - role: m4eba.etcd.install
      tags: install
      when: hostvars['localhost']['etcd_main'] is undefined

- name: handling pending
  hosts: etcd
  remote_user: root
  serial: 1
  roles:
    - role: m4eba.etcd.pending
      tags: pending
      when: ispending is defined

- name: add servers
  hosts: etcd
  remote_user: root
  serial: 1
  roles:
    - role: m4eba.etcd.add
      tags: add
      when: ispending is undefined and run_add is defined
